import type { Metadata } from 'next';
import type { ReactNode } from 'react';

/**
 * Thin root layout. The real <html>/<body> + providers live in
 * app/[lang]/layout.tsx, so the [lang] segment can resolve the locale first
 * (Fumadocs i18n pattern). This root only carries app-wide metadata and lets
 * the locale layouts (and the language-agnostic route handlers under /api,
 * /llms.txt, /robots) render their own output.
 *
 * Search indexing (production-only): the production deployment
 * (`VERCEL_ENV === 'production'`, i.e. www.gremorie.com) is indexable; every
 * other environment (preview/development) emits a `noindex` robots meta so
 * per-PR preview URLs never reach a search index. Vercel additionally sets its
 * own `X-Robots-Tag: noindex` on non-production deployments, so this is
 * defense-in-depth. `app/robots.ts` allows crawling in all environments (that
 * is what lets AI agents fetch the docs); indexing is gated here.
 *
 * Social metadata: metadataBase + openGraph/twitter live here so every route
 * inherits them; the og:image itself is generated by app/opengraph-image.tsx
 * and the favicon by app/icon.tsx (both Next metadata-route conventions).
 */
const siteTitle = 'Gremorie - the design system for React and Angular';
const siteDescription =
  '83 copy-paste primitives, tokens, and production blocks at parity across React and Angular. AI-native: registry + MCP server. Open source, MIT.';

const isProduction = process.env.VERCEL_ENV === 'production';

export const metadata: Metadata = {
  metadataBase: new URL('https://www.gremorie.com'),
  openGraph: {
    title: siteTitle,
    description: siteDescription,
    type: 'website',
    siteName: 'Gremorie',
    url: 'https://www.gremorie.com',
  },
  twitter: {
    card: 'summary_large_image',
    title: siteTitle,
    description: siteDescription,
  },
  robots: isProduction
    ? { index: true, follow: true }
    : {
        index: false,
        follow: false,
        nocache: true,
        googleBot: {
          index: false,
          follow: false,
          noimageindex: true,
        },
      },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return children;
}
