import type { Metadata } from 'next';
import type { ReactNode } from 'react';

/**
 * Thin root layout. The real <html>/<body> + providers live in
 * app/[lang]/layout.tsx, so the [lang] segment can resolve the locale first
 * (Fumadocs i18n pattern). This root only carries app-wide metadata and lets
 * the locale layouts (and the language-agnostic route handlers under /api,
 * /llms.txt, /robots) render their own output.
 *
 * Site-wide noindex (layer 1 of 3): emits `<meta name="robots">`. Also enforced
 * via app/robots.ts and the `X-Robots-Tag` header in vercel.json. Remove when
 * the site is ready for search-engine indexing (full SEO launch).
 *
 * Social metadata: metadataBase + openGraph/twitter live here so every route
 * inherits them; the og:image itself is generated by app/opengraph-image.tsx
 * and the favicon by app/icon.tsx (both Next metadata-route conventions).
 */
const siteTitle = 'Gremorie - the design system for React and Angular';
const siteDescription =
  '83 copy-paste primitives, tokens, and production blocks at parity across React and Angular. AI-native: registry + MCP server. Open source, MIT.';

export const metadata: Metadata = {
  metadataBase: new URL('https://www.gremorie.com'),
  openGraph: {
    title: siteTitle,
    description: siteDescription,
    type: 'website',
    siteName: 'Gremorie',
    url: 'https://www.gremorie.com',
  },
  twitter: {
    card: 'summary_large_image',
    title: siteTitle,
    description: siteDescription,
  },
  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: true,
    },
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return children;
}
