"use client";

import Link from "next/link";
import { ArrowRight, BarChart3, Code2 } from "lucide-react";
import { Button } from "@gremorie/rx-forms";
import {
  Badge,
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@gremorie/rx-display";
import { BarChart } from "@gremorie/rx-data";
import type { ChartConfig, Datum } from "@gremorie/rx-data";
import { CodeBlock } from "@gremorie/rx-ai";

/**
 * Spotlights two artifact types: Chart (data viz schema -> bar chart)
 * and Code (LLM emits code -> highlighted block with runtime preview).
 *
 * Dogfood: now uses the actual rx-data BarChart and rx-ai CodeBlock
 * primitives rendering real data, not styled divs / pre blocks. This
 * is the truest demonstration on the landing - the artifacts are the
 * same primitives shipped in the registry.
 */

const revenueData: Datum[] = [
  { month: "Jan", revenue: 42 },
  { month: "Feb", revenue: 58 },
  { month: "Mar", revenue: 51 },
  { month: "Apr", revenue: 66 },
  { month: "May", revenue: 74 },
  { month: "Jun", revenue: 69 },
  { month: "Jul", revenue: 82 },
  { month: "Aug", revenue: 87 },
  { month: "Sep", revenue: 79 },
  { month: "Oct", revenue: 93 },
  { month: "Nov", revenue: 97 },
  { month: "Dec", revenue: 100 },
];

const revenueConfig: ChartConfig = {
  revenue: { label: "Revenue", color: "var(--chart-1)" },
};

const SAMPLE_CODE = `// Generated by claude-opus-4-7
export function StatsCard({ label, value, delta }) {
  return (
    <Card>
      <CardHeader>{label}</CardHeader>
      <CardContent>
        <span>{value}</span>
        <Badge>{delta}</Badge>
      </CardContent>
    </Card>
  );
}`;

export function ArtifactsSpotlight() {
  return (
    <section className="py-20">
      <div className="mx-auto max-w-7xl px-6">
        <div className="mb-12 max-w-2xl">
          <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Generative UI artifacts
          </h2>
          <p className="mt-3 text-base text-muted-foreground">
            Render structured LLM output as production UI. Schema in,
            components out. Streaming-aware, type-safe, swappable.
          </p>
        </div>

        <div className="grid gap-6 lg:grid-cols-2">
          {/* Chart artifact - real BarChart from rx-data */}
          <Card className="gap-0 overflow-hidden py-0">
            <CardHeader className="flex-row items-center justify-between border-b border-border/60 py-3">
              <div className="flex items-center gap-2">
                <span className="inline-flex size-7 items-center justify-center rounded-md bg-primary/10 text-primary">
                  <BarChart3 className="size-3.5" aria-hidden="true" />
                </span>
                <div className="flex flex-col gap-0.5">
                  <CardTitle className="text-sm">Chart artifact</CardTitle>
                  <CardDescription className="text-xs">
                    Monthly revenue, last 12 months
                  </CardDescription>
                </div>
              </div>
              <Badge variant="outline" className="text-[10px] uppercase tracking-wider">
                Streaming
              </Badge>
            </CardHeader>

            <CardContent className="p-6">
              <BarChart
                data={revenueData}
                config={revenueConfig}
                xKey="month"
                className="border-0 p-0 shadow-none"
              />
            </CardContent>

            <CardFooter className="border-t border-border/60 p-0">
              <Button
                variant="ghost"
                className="h-auto w-full justify-start rounded-none px-5 py-3 text-xs font-medium"
                asChild
              >
                <Link href="/artifacts">
                  Learn more about chart artifacts
                  <ArrowRight aria-hidden="true" />
                </Link>
              </Button>
            </CardFooter>
          </Card>

          {/* Code artifact - real CodeBlock from rx-ai (shiki highlighting) */}
          <Card className="gap-0 overflow-hidden py-0">
            <CardHeader className="flex-row items-center justify-between border-b border-border/60 py-3">
              <div className="flex items-center gap-2">
                <span className="inline-flex size-7 items-center justify-center rounded-md bg-primary/10 text-primary">
                  <Code2 className="size-3.5" aria-hidden="true" />
                </span>
                <div className="flex flex-col gap-0.5">
                  <CardTitle className="text-sm">Code artifact</CardTitle>
                  <CardDescription className="text-xs">
                    Generated component, ts + tsx
                  </CardDescription>
                </div>
              </div>
              <Badge variant="outline" className="text-[10px] uppercase tracking-wider">
                Runtime
              </Badge>
            </CardHeader>

            <CardContent className="p-0">
              <CodeBlock
                code={SAMPLE_CODE}
                language="tsx"
                className="rounded-none border-0"
              />
            </CardContent>

            <CardFooter className="border-t border-border/60 p-0">
              <Button
                variant="ghost"
                className="h-auto w-full justify-start rounded-none px-5 py-3 text-xs font-medium"
                asChild
              >
                <Link href="/artifacts">
                  Learn more about code artifacts
                  <ArrowRight aria-hidden="true" />
                </Link>
              </Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </section>
  );
}
