import type { ItemConfig } from './types.js';

/**
 * The list of registry items to generate.
 *
 * Granularity rule: 1 item = 1 primitive (or a tight family of
 * sub-components that ALWAYS ship together). The npm packages stay as bundle
 * dist outputs (`@gremorie/ng-ai`, `@gremorie/ng-data`); the registry exposes
 * the same source per-primitive so consumers can `gremorie add ng-button`
 * without pulling in PromptInput.
 *
 * For Angular charts: a shared `ng-chart` base item carries the headless
 * primitives (chart-context, scales, axis, etc. plus all shape helpers).
 * Each styled chart (`ng-area-chart`, `ng-line-chart`, ...) ships only its
 * own styled wrapper and depends on `ng-chart` for the rest.
 *
 * `srcStrip` controls how source paths land in the consumer project. Using
 * the right value yields semantic target paths like
 * `src/app/gremorie/ai/prompt-input/prompt-input.ts` instead of the noisier
 * `src/app/gremorie/ai/lib/prompt-input/prompt-input.ts`.
 */
export const ITEMS: ItemConfig[] = [
  // ---------------------------------------------------------------------------
  // Angular: utilities & core primitives
  // ---------------------------------------------------------------------------
  {
    name: 'ng-utils',
    framework: 'ng',
    title: 'Utils (Angular)',
    description:
      'Shared utilities for the Angular edition - cn() helper that merges Tailwind class names with conflict resolution (clsx + tailwind-merge).',
    categories: ['core', 'utils'],
    packageRoot: 'packages/ng-core',
    sourceFiles: ['src/lib/utils.ts'],
    assetFiles: ['styles/theme.css'],
    targetPrefix: 'src/app/gremorie/utils',
    srcStrip: 'src/lib/',
    dependencies: ['clsx', 'tailwind-merge'],
    registryDependencies: [],
  },
  {
    name: 'ng-button',
    framework: 'ng',
    title: 'Button (Angular)',
    description:
      'Button primitive for the Angular edition - 6 variants x 4 sizes.',
    categories: ['core', 'primitives', 'forms'],
    packageRoot: 'packages/ng-core',
    sourceFiles: ['src/lib/button.ts'],
    targetPrefix: 'src/app/gremorie/button',
    srcStrip: 'src/lib/',
    dependencies: ['@angular/core', 'class-variance-authority'],
    registryDependencies: ['ng-utils'],
  },

  // ---------------------------------------------------------------------------
  // Angular: containers
  // ---------------------------------------------------------------------------
  {
    name: 'ng-scroll-area',
    framework: 'ng',
    title: 'Scroll Area (Angular)',
    description:
      'Thin design-system styling layer over ngx-scrollbar - overlay scrollbars with Gremorie tokens (thin, rounded, --border-colored thumb).',
    categories: ['containers', 'layout'],
    packageRoot: 'packages/ng-containers',
    sourceFiles: ['src/lib/scroll-area/scroll-area.ts'],
    targetPrefix: 'src/app/gremorie/scroll-area',
    srcStrip: 'src/lib/scroll-area/',
    dependencies: ['@angular/core', 'ngx-scrollbar'],
    registryDependencies: [],
  },

  // ---------------------------------------------------------------------------
  // Angular: display
  // ---------------------------------------------------------------------------
  {
    name: 'ng-card',
    framework: 'ng',
    title: 'Card (Angular)',
    description:
      'Compound surface for grouping related content - Card root with Header, Title, Description, Action, Content and Footer slots. Mirrors React Card from @gremorie/rx-display. Companion to Spartan-ng (fills the Card gap).',
    categories: ['display', 'primitives', 'layout'],
    packageRoot: 'packages/ng-display',
    sourceFiles: ['src/lib/card/card.ts', 'src/lib/card/index.ts'],
    targetPrefix: 'src/app/gremorie/card',
    srcStrip: 'src/lib/card/',
    dependencies: ['@angular/core'],
    registryDependencies: [],
  },
  {
    name: 'ng-badge',
    framework: 'ng',
    title: 'Badge (Angular)',
    description:
      'Compact label for status, counts and tags - 6 variants (default, secondary, destructive, outline, ghost, link). Token-driven so theme changes propagate automatically. Mirrors React Badge from @gremorie/rx-display. Companion to Spartan-ng (fills the Badge gap).',
    categories: ['display', 'primitives'],
    packageRoot: 'packages/ng-display',
    sourceFiles: ['src/lib/badge/badge.ts', 'src/lib/badge/index.ts'],
    targetPrefix: 'src/app/gremorie/badge',
    srcStrip: 'src/lib/badge/',
    dependencies: ['@angular/core', 'class-variance-authority'],
    registryDependencies: [],
  },

  // ---------------------------------------------------------------------------
  // Angular: AI primitives
  // ---------------------------------------------------------------------------
  {
    name: 'ng-attachments',
    framework: 'ng',
    title: 'Attachments (Angular)',
    description:
      'Composable Attachment* family - List, Item, Preview, Info, Name, Size, Remove, Empty - plus type and util files. Lays out file attachments for chat surfaces.',
    categories: ['ai', 'forms', 'media'],
    packageRoot: 'packages/ng-ai',
    sourceFiles: [
      'src/lib/attachments/attachment.types.ts',
      'src/lib/attachments/attachment.utils.ts',
      'src/lib/attachments/attachment-empty.ts',
      'src/lib/attachments/attachment-info.ts',
      'src/lib/attachments/attachment-item.ts',
      'src/lib/attachments/attachment-list.ts',
      'src/lib/attachments/attachment-name.ts',
      'src/lib/attachments/attachment-preview.ts',
      'src/lib/attachments/attachment-remove.ts',
      'src/lib/attachments/attachment-size.ts',
    ],
    targetPrefix: 'src/app/gremorie/ai/attachments',
    srcStrip: 'src/lib/attachments/',
    dependencies: [
      '@angular/core',
      '@angular/common',
      'class-variance-authority',
    ],
    registryDependencies: [],
  },
  {
    name: 'ng-prompt-input',
    framework: 'ng',
    title: 'Prompt Input (Angular)',
    description:
      'PromptInput family for AI chat surfaces - state machine (ready -> submitted -> streaming -> error), drag-drop, paste-to-attach. Ships textarea, submit, toolbar, tools, action-menu, model-select sub-components that compose together.',
    categories: ['ai', 'forms'],
    packageRoot: 'packages/ng-ai',
    sourceFiles: [
      'src/lib/prompt-input/prompt-input.types.ts',
      'src/lib/prompt-input/prompt-input.ts',
      'src/lib/prompt-input/prompt-input-textarea.ts',
      'src/lib/prompt-input/prompt-input-submit.ts',
      'src/lib/prompt-input/prompt-input-toolbar.ts',
      'src/lib/prompt-input/prompt-input-tools.ts',
      'src/lib/prompt-input/prompt-input-action-menu.ts',
      'src/lib/prompt-input/prompt-input-model-select.ts',
    ],
    targetPrefix: 'src/app/gremorie/ai/prompt-input',
    srcStrip: 'src/lib/prompt-input/',
    dependencies: [
      '@angular/core',
      '@angular/common',
      'class-variance-authority',
    ],
    // ng-utils for cn(); ng-attachments for the relative imports from
    // prompt-input.ts (../attachments/attachment.utils + types). The
    // relative imports resolve when both items live under
    // src/app/gremorie/ai/.
    registryDependencies: ['ng-utils', 'ng-attachments'],
  },
  {
    name: 'ng-message',
    framework: 'ng',
    title: 'Message (Angular)',
    description:
      'Message family for chat bubbles - root + content, avatar, actions, toolbar, attachments, response. Includes branch sub-family (controllable picker over alternative responses).',
    categories: ['ai', 'chat'],
    packageRoot: 'packages/ng-ai',
    sourceFiles: [
      'src/lib/message/message.types.ts',
      'src/lib/message/message.ts',
      'src/lib/message/message-content.ts',
      'src/lib/message/message-avatar.ts',
      'src/lib/message/message-actions.ts',
      'src/lib/message/message-toolbar.ts',
      'src/lib/message/message-attachments.ts',
      'src/lib/message/message-attachment.ts',
      'src/lib/message/message-response.ts',
      'src/lib/message/message-branch.ts',
      'src/lib/message/message-branch-content.ts',
      'src/lib/message/message-branch-selector.ts',
      'src/lib/message/message-branch-controls.ts',
      'src/lib/message/index.ts',
    ],
    targetPrefix: 'src/app/gremorie/ai/message',
    srcStrip: 'src/lib/message/',
    dependencies: ['@angular/core', '@angular/common'],
    registryDependencies: ['ng-utils'],
  },
  {
    name: 'ng-conversation',
    framework: 'ng',
    title: 'Conversation (Angular)',
    description:
      'Scrollable chat log with auto-stick-to-bottom behavior, empty state and a scroll-to-bottom pill that appears when the user scrolls up.',
    categories: ['ai', 'chat'],
    packageRoot: 'packages/ng-ai',
    sourceFiles: [
      'src/lib/conversation/conversation.ts',
      'src/lib/conversation/conversation-content.ts',
      'src/lib/conversation/conversation-empty-state.ts',
      'src/lib/conversation/conversation-scroll-button.ts',
      'src/lib/conversation/index.ts',
    ],
    targetPrefix: 'src/app/gremorie/ai/conversation',
    srcStrip: 'src/lib/conversation/',
    dependencies: ['@angular/core'],
    registryDependencies: [],
  },
  {
    name: 'ng-suggestion',
    framework: 'ng',
    title: 'Suggestion (Angular)',
    description:
      'Suggestion chips for AI prompts - horizontal scrollable Suggestions container with rounded-full Suggestion buttons that emit `(select)` carrying the value.',
    categories: ['ai', 'forms'],
    packageRoot: 'packages/ng-ai',
    sourceFiles: [
      'src/lib/suggestion/suggestion.ts',
      'src/lib/suggestion/suggestions.ts',
      'src/lib/suggestion/index.ts',
    ],
    targetPrefix: 'src/app/gremorie/ai/suggestion',
    srcStrip: 'src/lib/suggestion/',
    dependencies: ['@angular/core', 'class-variance-authority'],
    registryDependencies: ['ng-utils'],
  },
  {
    name: 'ng-shimmer',
    framework: 'ng',
    title: 'Shimmer (Angular)',
    description:
      'Standalone directive that applies a sweeping gradient animation to text - used for streaming/loading states. Same visual effect as the rx-ai counterpart (motion/react), implemented natively with CSS keyframes (no runtime motion lib).',
    categories: ['ai', 'feedback'],
    packageRoot: 'packages/ng-ai',
    sourceFiles: ['src/lib/shimmer/shimmer.ts', 'src/lib/shimmer/index.ts'],
    targetPrefix: 'src/app/gremorie/ai/shimmer',
    srcStrip: 'src/lib/shimmer/',
    dependencies: ['@angular/core'],
    registryDependencies: [],
  },
  {
    name: 'ng-reasoning',
    framework: 'ng',
    title: 'Reasoning (Angular)',
    description:
      'Collapsible "thinking..." block with auto-open while streaming, auto-close once streaming ends and duration tracking. Composes Reasoning + ReasoningTrigger + ReasoningContent, built on @spartan-ng/brain/collapsible.',
    categories: ['ai', 'chat'],
    packageRoot: 'packages/ng-ai',
    sourceFiles: [
      'src/lib/reasoning/reasoning.ts',
      'src/lib/reasoning/reasoning-trigger.ts',
      'src/lib/reasoning/reasoning-content.ts',
      'src/lib/reasoning/index.ts',
    ],
    targetPrefix: 'src/app/gremorie/ai/reasoning',
    srcStrip: 'src/lib/reasoning/',
    dependencies: ['@angular/core', '@spartan-ng/brain'],
    registryDependencies: ['ng-utils', 'ng-shimmer'],
  },
  {
    name: 'ng-chain-of-thought',
    framework: 'ng',
    title: 'Chain of Thought (Angular)',
    description:
      'Step-by-step reasoning trace - root container, clickable header, content panel, individual steps (complete/active/pending status), search-result chips and bounded image previews.',
    categories: ['ai', 'chat'],
    packageRoot: 'packages/ng-ai',
    sourceFiles: [
      'src/lib/chain-of-thought/chain-of-thought.ts',
      'src/lib/chain-of-thought/chain-of-thought-header.ts',
      'src/lib/chain-of-thought/chain-of-thought-content.ts',
      'src/lib/chain-of-thought/chain-of-thought-step.ts',
      'src/lib/chain-of-thought/chain-of-thought-search.ts',
      'src/lib/chain-of-thought/chain-of-thought-image.ts',
      'src/lib/chain-of-thought/index.ts',
    ],
    targetPrefix: 'src/app/gremorie/ai/chain-of-thought',
    srcStrip: 'src/lib/chain-of-thought/',
    dependencies: ['@angular/core'],
    registryDependencies: ['ng-utils'],
  },
  {
    name: 'ng-sources',
    framework: 'ng',
    title: 'Sources (Angular)',
    description:
      'Citation list for AI responses - collapsible container, header trigger ("Used {count} sources"), content panel and Source link items.',
    categories: ['ai', 'chat'],
    packageRoot: 'packages/ng-ai',
    sourceFiles: [
      'src/lib/sources/sources.ts',
      'src/lib/sources/sources-trigger.ts',
      'src/lib/sources/sources-content.ts',
      'src/lib/sources/source.ts',
      'src/lib/sources/index.ts',
    ],
    targetPrefix: 'src/app/gremorie/ai/sources',
    srcStrip: 'src/lib/sources/',
    dependencies: ['@angular/core'],
    registryDependencies: [],
  },
  {
    name: 'ng-task',
    framework: 'ng',
    title: 'Task (Angular)',
    description:
      'Collapsible task card with file attachments - Task container, TaskTrigger header (search icon + title + chevron), TaskContent body with left-border list, TaskItem rows and TaskItemFile chips.',
    categories: ['ai', 'chat'],
    packageRoot: 'packages/ng-ai',
    sourceFiles: [
      'src/lib/task/task.ts',
      'src/lib/task/task-trigger.ts',
      'src/lib/task/task-content.ts',
      'src/lib/task/task-item.ts',
      'src/lib/task/index.ts',
    ],
    targetPrefix: 'src/app/gremorie/ai/task',
    srcStrip: 'src/lib/task/',
    dependencies: ['@angular/core'],
    registryDependencies: [],
  },
  {
    name: 'ng-tool',
    framework: 'ng',
    title: 'Tool (Angular)',
    description:
      'State-machine card for AI SDK tool invocations - Tool container, ToolHeader with state badge (Pending/Running/Awaiting Approval/Responded/Completed/Error/Denied), ToolContent body, ToolInput (parameters JSON), ToolOutput (result or error).',
    categories: ['ai', 'chat'],
    packageRoot: 'packages/ng-ai',
    sourceFiles: [
      'src/lib/tool/tool.types.ts',
      'src/lib/tool/tool.ts',
      'src/lib/tool/tool-header.ts',
      'src/lib/tool/tool-content.ts',
      'src/lib/tool/tool-input.ts',
      'src/lib/tool/tool-output.ts',
      'src/lib/tool/index.ts',
    ],
    targetPrefix: 'src/app/gremorie/ai/tool',
    srcStrip: 'src/lib/tool/',
    dependencies: ['@angular/core'],
    registryDependencies: ['ng-utils'],
  },
  {
    name: 'ng-toolbar',
    framework: 'ng',
    title: 'Toolbar (Angular)',
    description:
      'Generic action toolbar for AI message contexts - Toolbar row, ToolbarGroup (orientation-aware visually-grouped subset), ToolbarButton (with optional pressed toggle state).',
    categories: ['ai', 'chat'],
    packageRoot: 'packages/ng-ai',
    sourceFiles: [
      'src/lib/toolbar/toolbar.ts',
      'src/lib/toolbar/toolbar-group.ts',
      'src/lib/toolbar/toolbar-button.ts',
      'src/lib/toolbar/index.ts',
    ],
    targetPrefix: 'src/app/gremorie/ai/toolbar',
    srcStrip: 'src/lib/toolbar/',
    dependencies: ['@angular/core'],
    registryDependencies: ['ng-utils'],
  },
  {
    name: 'ng-code-block',
    framework: 'ng',
    title: 'Code Block (Angular)',
    description:
      'Shiki-highlighted code container with light/dark theme snapshots and an optional copy button. Mirrors the rx-ai implementation (github-light-default / github-dark-default).',
    categories: ['ai', 'code'],
    packageRoot: 'packages/ng-ai',
    sourceFiles: [
      'src/lib/code-block/code-block.ts',
      'src/lib/code-block/code-block-copy-button.ts',
      'src/lib/code-block/index.ts',
    ],
    targetPrefix: 'src/app/gremorie/ai/code-block',
    srcStrip: 'src/lib/code-block/',
    dependencies: ['@angular/core', 'shiki'],
    registryDependencies: ['ng-utils'],
  },

  // ---------------------------------------------------------------------------
  // Angular: data viz - shared chart engine
  // ---------------------------------------------------------------------------
  {
    name: 'ng-chart',
    framework: 'ng',
    title: 'Chart (Angular)',
    description:
      'Headless chart engine for the Angular edition - chart-context, scales, axis, cartesian-grid, chart-frame, plus shape helpers (area, line, bar, scatter, pie, polar, radar, radial-bar). Shared base for every styled chart.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/ng-data',
    sourceFiles: [
      'src/lib/charts/headless/types.ts',
      'src/lib/charts/headless/format.ts',
      'src/lib/charts/headless/scales.ts',
      'src/lib/charts/headless/shape.ts',
      'src/lib/charts/headless/domain.ts',
      'src/lib/charts/headless/chart-context.ts',
      'src/lib/charts/headless/axis.ts',
      'src/lib/charts/headless/chart-frame.ts',
      'src/lib/charts/headless/cartesian-grid.ts',
      'src/lib/charts/headless/area.ts',
      'src/lib/charts/headless/line.ts',
      'src/lib/charts/headless/bar.ts',
      'src/lib/charts/headless/scatter.ts',
      'src/lib/charts/headless/polar.ts',
      'src/lib/charts/headless/pie.ts',
      'src/lib/charts/headless/radar.ts',
      'src/lib/charts/headless/radial-bar.ts',
    ],
    targetPrefix: 'src/app/gremorie/data/headless',
    srcStrip: 'src/lib/charts/headless/',
    dependencies: ['@angular/core', 'd3-scale', 'd3-shape', 'd3-format'],
    registryDependencies: ['ng-utils'],
  },

  // ---------------------------------------------------------------------------
  // Angular: data viz - styled charts (one per shape)
  // ---------------------------------------------------------------------------
  {
    name: 'ng-area-chart',
    framework: 'ng',
    title: 'Area Chart (Angular)',
    description:
      'Styled area chart - cumulative quantity over a continuous domain. Uses the ng-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/ng-data',
    sourceFiles: ['src/lib/charts/styled/area-chart.ts'],
    targetPrefix: 'src/app/gremorie/data/area-chart',
    srcStrip: 'src/lib/charts/styled/',
    dependencies: ['@angular/core'],
    registryDependencies: ['ng-utils', 'ng-chart'],
  },
  {
    name: 'ng-line-chart',
    framework: 'ng',
    title: 'Line Chart (Angular)',
    description:
      'Styled line chart - trends over a continuous domain. Uses the ng-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/ng-data',
    sourceFiles: ['src/lib/charts/styled/line-chart.ts'],
    targetPrefix: 'src/app/gremorie/data/line-chart',
    srcStrip: 'src/lib/charts/styled/',
    dependencies: ['@angular/core'],
    registryDependencies: ['ng-utils', 'ng-chart'],
  },
  {
    name: 'ng-bar-chart',
    framework: 'ng',
    title: 'Bar Chart (Angular)',
    description:
      'Styled bar chart - categorical comparison. Uses the ng-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/ng-data',
    sourceFiles: ['src/lib/charts/styled/bar-chart.ts'],
    targetPrefix: 'src/app/gremorie/data/bar-chart',
    srcStrip: 'src/lib/charts/styled/',
    dependencies: ['@angular/core'],
    registryDependencies: ['ng-utils', 'ng-chart'],
  },
  {
    name: 'ng-scatter-chart',
    framework: 'ng',
    title: 'Scatter Chart (Angular)',
    description:
      'Styled scatter chart - x/y distribution. Uses the ng-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/ng-data',
    sourceFiles: ['src/lib/charts/styled/scatter-chart.ts'],
    targetPrefix: 'src/app/gremorie/data/scatter-chart',
    srcStrip: 'src/lib/charts/styled/',
    dependencies: ['@angular/core'],
    registryDependencies: ['ng-utils', 'ng-chart'],
  },
  {
    name: 'ng-pie-chart',
    framework: 'ng',
    title: 'Pie Chart (Angular)',
    description:
      'Styled pie chart - part-to-whole. Uses the ng-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/ng-data',
    sourceFiles: ['src/lib/charts/styled/pie-chart.ts'],
    targetPrefix: 'src/app/gremorie/data/pie-chart',
    srcStrip: 'src/lib/charts/styled/',
    dependencies: ['@angular/core'],
    registryDependencies: ['ng-utils', 'ng-chart'],
  },
  {
    name: 'ng-radar-chart',
    framework: 'ng',
    title: 'Radar Chart (Angular)',
    description:
      'Styled radar chart - multi-axis comparison. Uses the ng-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/ng-data',
    sourceFiles: ['src/lib/charts/styled/radar-chart.ts'],
    targetPrefix: 'src/app/gremorie/data/radar-chart',
    srcStrip: 'src/lib/charts/styled/',
    dependencies: ['@angular/core'],
    registryDependencies: ['ng-utils', 'ng-chart'],
  },
  {
    name: 'ng-radial-chart',
    framework: 'ng',
    title: 'Radial Chart (Angular)',
    description:
      'Styled radial-bar chart - progress / gauge metaphor. Uses the ng-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/ng-data',
    sourceFiles: ['src/lib/charts/styled/radial-chart.ts'],
    targetPrefix: 'src/app/gremorie/data/radial-chart',
    srcStrip: 'src/lib/charts/styled/',
    dependencies: ['@angular/core'],
    registryDependencies: ['ng-utils', 'ng-chart'],
  },

  // ---------------------------------------------------------------------------
  // React (rx-*): pilot
  // ---------------------------------------------------------------------------
  {
    name: 'rx-utils',
    framework: 'rx',
    title: 'Utils (React)',
    description:
      'Shared utilities for the React edition - cn() helper that merges Tailwind class names with conflict resolution (clsx + tailwind-merge).',
    categories: ['core', 'utils'],
    packageRoot: 'packages/rx-core',
    sourceFiles: ['src/lib/utils.ts'],
    targetPrefix: 'src/components/gremorie/utils',
    srcStrip: 'src/lib/',
    dependencies: ['clsx', 'tailwind-merge'],
    registryDependencies: [],
  },
  {
    name: 'rx-button',
    framework: 'rx',
    title: 'Button (React)',
    description:
      'Button primitive for the React edition - 6 variants x 8 sizes (including icon-only), `asChild` via Radix Slot.',
    categories: ['core', 'primitives', 'forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/button/button.tsx'],
    targetPrefix: 'src/components/gremorie/forms/button',
    srcStrip: 'src/lib/button/',
    dependencies: ['class-variance-authority', 'radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-input',
    framework: 'rx',
    title: 'Input (React)',
    description:
      'Input primitive for the React edition - single-line text field that adopts every native HTML `type`. Token-driven visual states.',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/input/input.tsx'],
    targetPrefix: 'src/components/gremorie/forms/input',
    srcStrip: 'src/lib/input/',
    dependencies: [],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-label',
    framework: 'rx',
    title: 'Label (React)',
    description:
      'Label primitive built on `@radix-ui/react-label` (via `radix-ui` namespace). Pair with Input / form controls.',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/label/label.tsx'],
    targetPrefix: 'src/components/gremorie/forms/label',
    srcStrip: 'src/lib/label/',
    dependencies: ['radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-select',
    framework: 'rx',
    title: 'Select (React)',
    description:
      'Select primitive built on Radix Select - portalled, animated listbox, grouped items, scroll buttons. For short fixed lists (5-30 options).',
    categories: ['forms', 'overlays'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/select/select.tsx'],
    targetPrefix: 'src/components/gremorie/forms/select',
    srcStrip: 'src/lib/select/',
    dependencies: ['radix-ui', 'lucide-react'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-textarea',
    framework: 'rx',
    title: 'Textarea (React)',
    description:
      'Multi-line text field that auto-grows via `field-sizing: content`. Use for free-form input where rows are unknown ahead of time.',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/textarea/textarea.tsx'],
    targetPrefix: 'src/components/gremorie/forms/textarea',
    srcStrip: 'src/lib/textarea/',
    dependencies: [],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-input-group',
    framework: 'rx',
    title: 'Input Group (React)',
    description:
      'Composable input layout - wraps Input or Textarea with inline / block addons (icons, buttons, kbd hints). Drives focus + invalid + disabled states from the inner control. Enables the InputGroupButton composition that powers PromptInput.',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/input-group/input-group.tsx'],
    targetPrefix: 'src/components/gremorie/forms/input-group',
    srcStrip: 'src/lib/input-group/',
    dependencies: ['class-variance-authority'],
    registryDependencies: [
      'rx-utils',
      'rx-button',
      'rx-input',
      'rx-textarea',
    ],
  },
  {
    name: 'rx-dropdown-menu',
    framework: 'rx',
    title: 'Dropdown Menu (React)',
    description:
      'DropdownMenu family built on Radix DropdownMenu - actions menu with checkbox / radio items, separators, nested submenus, destructive variant.',
    categories: ['overlays'],
    packageRoot: 'packages/rx-overlays',
    sourceFiles: ['src/lib/dropdown-menu/dropdown-menu.tsx'],
    targetPrefix: 'src/components/gremorie/overlays/dropdown-menu',
    srcStrip: 'src/lib/dropdown-menu/',
    dependencies: ['radix-ui', 'lucide-react'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-hover-card',
    framework: 'rx',
    title: 'Hover Card (React)',
    description:
      'HoverCard primitive built on Radix HoverCard - non-interactive preview pane shown on hover. Use for link previews, profile cards, image teasers.',
    categories: ['overlays'],
    packageRoot: 'packages/rx-overlays',
    sourceFiles: ['src/lib/hover-card/hover-card.tsx'],
    targetPrefix: 'src/components/gremorie/overlays/hover-card',
    srcStrip: 'src/lib/hover-card/',
    dependencies: ['radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-dialog',
    framework: 'rx',
    title: 'Dialog (React)',
    description:
      'Modal overlay anchored at viewport center, built on Radix Dialog. Use for focused decisions or short flows that need to interrupt the user context - confirmations, single-step forms, detail cards.',
    categories: ['overlays'],
    packageRoot: 'packages/rx-overlays',
    sourceFiles: ['src/lib/dialog/dialog.tsx'],
    targetPrefix: 'src/components/gremorie/overlays/dialog',
    srcStrip: 'src/lib/dialog/',
    dependencies: ['radix-ui', 'lucide-react'],
    registryDependencies: ['rx-utils', 'rx-button'],
  },
  {
    name: 'rx-sheet',
    framework: 'rx',
    title: 'Sheet (React)',
    description:
      'Side-anchored panel for longer flows, built on Radix Dialog with a directional slide animation. Use for filters, settings panels, multi-section edit forms.',
    categories: ['overlays'],
    packageRoot: 'packages/rx-overlays',
    sourceFiles: ['src/lib/sheet/sheet.tsx'],
    targetPrefix: 'src/components/gremorie/overlays/sheet',
    srcStrip: 'src/lib/sheet/',
    dependencies: ['radix-ui', 'lucide-react'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-popover',
    framework: 'rx',
    title: 'Popover (React)',
    description:
      'Anchored interactive content overlay built on Radix Popover. Triggers on click and hosts interactive content - date pickers, mini forms, share menus. Distinct from Tooltip (hover-only) and HoverCard (hover previews).',
    categories: ['overlays'],
    packageRoot: 'packages/rx-overlays',
    sourceFiles: ['src/lib/popover/popover.tsx'],
    targetPrefix: 'src/components/gremorie/overlays/popover',
    srcStrip: 'src/lib/popover/',
    dependencies: ['radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-tooltip',
    framework: 'rx',
    title: 'Tooltip (React)',
    description:
      'Short non-essential context on hover/focus, built on Radix Tooltip. Reserve for non-critical supporting information - keyboard shortcuts, icon labels, "what does this do" hints. Wrap your app root in `<TooltipProvider>` so all tooltips share a delay timer.',
    categories: ['overlays'],
    packageRoot: 'packages/rx-overlays',
    sourceFiles: ['src/lib/tooltip/tooltip.tsx'],
    targetPrefix: 'src/components/gremorie/overlays/tooltip',
    srcStrip: 'src/lib/tooltip/',
    dependencies: ['radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-command',
    framework: 'rx',
    title: 'Command (React)',
    description:
      'Command palette primitive built on cmdk - inline picker (Combobox pattern) for keyboard-first navigation, plus CommandDialog for the canonical Cmd+K floating palette.',
    categories: ['overlays', 'navigation'],
    packageRoot: 'packages/rx-overlays',
    sourceFiles: ['src/lib/command/command.tsx'],
    targetPrefix: 'src/components/gremorie/overlays/command',
    srcStrip: 'src/lib/command/',
    dependencies: ['cmdk', 'lucide-react'],
    registryDependencies: ['rx-utils', 'rx-dialog'],
  },
  {
    name: 'rx-alert-dialog',
    framework: 'rx',
    title: 'Alert Dialog (React)',
    description:
      'Modal-blocking confirmation dialog built on Radix AlertDialog. Use for destructive confirmations and irreversible actions - the user must choose, no close-on-overlay or close-on-escape.',
    categories: ['overlays'],
    packageRoot: 'packages/rx-overlays',
    sourceFiles: ['src/lib/alert-dialog/alert-dialog.tsx'],
    targetPrefix: 'src/components/gremorie/overlays/alert-dialog',
    srcStrip: 'src/lib/alert-dialog/',
    dependencies: ['radix-ui'],
    registryDependencies: ['rx-utils', 'rx-button'],
  },
  {
    name: 'rx-context-menu',
    framework: 'rx',
    title: 'Context Menu (React)',
    description:
      'Secondary action menu invoked via right-click, built on Radix ContextMenu. Power-user accelerator with the same shape as DropdownMenu (items, groups, separators, sub-menus, checkbox/radio variants).',
    categories: ['overlays'],
    packageRoot: 'packages/rx-overlays',
    sourceFiles: ['src/lib/context-menu/context-menu.tsx'],
    targetPrefix: 'src/components/gremorie/overlays/context-menu',
    srcStrip: 'src/lib/context-menu/',
    dependencies: ['radix-ui', 'lucide-react'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-drawer',
    framework: 'rx',
    title: 'Drawer (React)',
    description:
      'Bottom-up sheet for mobile contexts, built on vaul. Slides up from the bottom by default with native gesture support (drag-to-dismiss, momentum). Best for mobile confirmations, quick actions, simple forms.',
    categories: ['overlays'],
    packageRoot: 'packages/rx-overlays',
    sourceFiles: ['src/lib/drawer/drawer.tsx'],
    targetPrefix: 'src/components/gremorie/overlays/drawer',
    srcStrip: 'src/lib/drawer/',
    dependencies: ['vaul'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-sonner',
    framework: 'rx',
    title: 'Sonner (React)',
    description:
      'Toast notification root, wraps `sonner` with Gremorie tokens. Mount once at the app root - any descendant can fire `toast()` without an additional provider. For transient feedback only - for persistent in-flow messages use Alert; for critical confirmations use AlertDialog.',
    categories: ['overlays', 'feedback'],
    packageRoot: 'packages/rx-overlays',
    sourceFiles: ['src/lib/sonner/sonner.tsx'],
    targetPrefix: 'src/components/gremorie/overlays/sonner',
    srcStrip: 'src/lib/sonner/',
    dependencies: ['sonner', 'lucide-react'],
    registryDependencies: [],
  },
  {
    name: 'rx-date-picker',
    framework: 'rx',
    title: 'Date Picker (React)',
    description:
      'Composite of Popover + Calendar with Gremorie defaults. Single-mode by default. Lives in rx-overlays because it composes Popover (rx-overlays) with Button + Calendar (rx-forms).',
    categories: ['forms', 'overlays'],
    packageRoot: 'packages/rx-overlays',
    sourceFiles: ['src/lib/date-picker/date-picker.tsx'],
    targetPrefix: 'src/components/gremorie/forms/date-picker',
    srcStrip: 'src/lib/date-picker/',
    dependencies: ['date-fns', 'lucide-react'],
    registryDependencies: ['rx-utils', 'rx-button', 'rx-calendar', 'rx-popover'],
  },

  // ---------------------------------------------------------------------------
  // React (rx-*): display primitives
  // ---------------------------------------------------------------------------
  {
    name: 'rx-accordion',
    framework: 'rx',
    title: 'Accordion (React)',
    description:
      'Vertically stacked, coordinated expandable sections built on Radix Accordion. Use when multiple sections share a common rhythm (FAQ, settings groups). For a single expandable region, use Collapsible.',
    categories: ['display'],
    packageRoot: 'packages/rx-display',
    sourceFiles: ['src/lib/accordion/accordion.tsx'],
    targetPrefix: 'src/components/gremorie/display/accordion',
    srcStrip: 'src/lib/accordion/',
    dependencies: ['radix-ui', 'lucide-react'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-avatar',
    framework: 'rx',
    title: 'Avatar (React)',
    description:
      'User identity glyph built on Radix Avatar - image with graceful fallback to initials or icon. Use for user surfaces (header, comments, mention chips, settings).',
    categories: ['display'],
    packageRoot: 'packages/rx-display',
    sourceFiles: ['src/lib/avatar/avatar.tsx'],
    targetPrefix: 'src/components/gremorie/display/avatar',
    srcStrip: 'src/lib/avatar/',
    dependencies: ['radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-badge',
    framework: 'rx',
    title: 'Badge (React)',
    description:
      'Compact label for status, count, or category. Variants: default, secondary, destructive, outline. Supports `asChild` via Radix Slot for composition with links/buttons.',
    categories: ['display'],
    packageRoot: 'packages/rx-display',
    sourceFiles: ['src/lib/badge/badge.tsx'],
    targetPrefix: 'src/components/gremorie/display/badge',
    srcStrip: 'src/lib/badge/',
    dependencies: ['class-variance-authority', 'radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-card',
    framework: 'rx',
    title: 'Card (React)',
    description:
      'Surface container for grouped content - composes CardHeader, CardTitle, CardDescription, CardContent, CardFooter. The base building block for dashboards, lists, and modal-less detail views.',
    categories: ['display'],
    packageRoot: 'packages/rx-display',
    sourceFiles: ['src/lib/card/card.tsx'],
    targetPrefix: 'src/components/gremorie/display/card',
    srcStrip: 'src/lib/card/',
    dependencies: [],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-carousel',
    framework: 'rx',
    title: 'Carousel (React)',
    description:
      'Horizontal slider built on embla-carousel-react - touch / drag, keyboard navigation, pagination dots, prev/next controls. Best for hero rotators, image galleries, onboarding tours.',
    categories: ['display'],
    packageRoot: 'packages/rx-display',
    sourceFiles: ['src/lib/carousel/carousel.tsx'],
    targetPrefix: 'src/components/gremorie/display/carousel',
    srcStrip: 'src/lib/carousel/',
    dependencies: ['embla-carousel-react', 'lucide-react'],
    registryDependencies: ['rx-utils', 'rx-button'],
  },
  {
    name: 'rx-collapsible',
    framework: 'rx',
    title: 'Collapsible (React)',
    description:
      'Single-section expandable region built on Radix Collapsible. Minimal building block for "show more" toggles, sidebar group expand/collapse, inline disclosures.',
    categories: ['display'],
    packageRoot: 'packages/rx-display',
    sourceFiles: ['src/lib/collapsible/collapsible.tsx'],
    targetPrefix: 'src/components/gremorie/display/collapsible',
    srcStrip: 'src/lib/collapsible/',
    dependencies: ['radix-ui'],
    registryDependencies: [],
  },
  {
    name: 'rx-separator',
    framework: 'rx',
    title: 'Separator (React)',
    description:
      'Horizontal or vertical visual divider built on Radix Separator. Use sparingly - prefer spacing for visual grouping; reach for Separator only when a hard line carries semantic meaning.',
    categories: ['display'],
    packageRoot: 'packages/rx-display',
    sourceFiles: ['src/lib/separator/separator.tsx'],
    targetPrefix: 'src/components/gremorie/display/separator',
    srcStrip: 'src/lib/separator/',
    dependencies: ['radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-table',
    framework: 'rx',
    title: 'Table (React)',
    description:
      'Styled wrapper over native HTML `<table>` - composable Table, TableHeader, TableBody, TableFooter, TableRow, TableHead, TableCell, TableCaption. Use for tabular data; pair with a data-grid library for sorting, filtering, virtualization.',
    categories: ['display'],
    packageRoot: 'packages/rx-display',
    sourceFiles: ['src/lib/table/table.tsx'],
    targetPrefix: 'src/components/gremorie/display/table',
    srcStrip: 'src/lib/table/',
    dependencies: [],
    registryDependencies: ['rx-utils'],
  },

  // ---------------------------------------------------------------------------
  // React (rx-*): container primitives
  // ---------------------------------------------------------------------------
  {
    name: 'rx-aspect-ratio',
    framework: 'rx',
    title: 'Aspect Ratio (React)',
    description:
      'Reserves vertical space for media before content loads - thin wrapper over Radix AspectRatio. Use on responsive images, iframes, video embeds, and skeleton placeholders to prevent cumulative layout shift.',
    categories: ['containers'],
    packageRoot: 'packages/rx-containers',
    sourceFiles: ['src/lib/aspect-ratio/aspect-ratio.tsx'],
    targetPrefix: 'src/components/gremorie/containers/aspect-ratio',
    srcStrip: 'src/lib/aspect-ratio/',
    dependencies: ['radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-resizable',
    framework: 'rx',
    title: 'Resizable (React)',
    description:
      'Split panes with draggable handles - ResizablePanelGroup + ResizablePanel + ResizableHandle on top of react-resizable-panels. Use for dev tools and pro apps (editors, email clients, file managers); consumer surfaces almost always read better with fixed proportions.',
    categories: ['containers'],
    packageRoot: 'packages/rx-containers',
    sourceFiles: ['src/lib/resizable/resizable.tsx'],
    targetPrefix: 'src/components/gremorie/containers/resizable',
    srcStrip: 'src/lib/resizable/',
    dependencies: ['react-resizable-panels', 'lucide-react'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-scroll-area',
    framework: 'rx',
    title: 'Scroll Area (React)',
    description:
      'Themeable scroll container built on Radix ScrollArea - ScrollArea + ScrollBar. Reach for it when you need consistent scrollbar styling across OSs, or when the scrollbar lives inside a rounded card and the native bar would bleed outside the radius. Otherwise native scroll is fine.',
    categories: ['containers'],
    packageRoot: 'packages/rx-containers',
    sourceFiles: ['src/lib/scroll-area/scroll-area.tsx'],
    targetPrefix: 'src/components/gremorie/containers/scroll-area',
    srcStrip: 'src/lib/scroll-area/',
    dependencies: ['radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-stack',
    framework: 'rx',
    title: 'Stack (React)',
    description:
      'Vertical layout primitive - a `<div>` configured as flex column with consistent gap, align, and justify props. The right choice for any list flowing top-to-bottom (card contents, form sections, settings rows, vertical menus).',
    categories: ['containers'],
    packageRoot: 'packages/rx-containers',
    sourceFiles: ['src/lib/stack/stack.tsx'],
    targetPrefix: 'src/components/gremorie/containers/stack',
    srcStrip: 'src/lib/stack/',
    dependencies: ['class-variance-authority'],
    registryDependencies: ['rx-utils'],
  },

  // ---------------------------------------------------------------------------
  // React (rx-*): feedback primitives
  // ---------------------------------------------------------------------------
  {
    name: 'rx-alert',
    framework: 'rx',
    title: 'Alert (React)',
    description:
      'Persistent in-flow feedback message - distinct from Sonner (transient) and AlertDialog (modal). Two variants (default, destructive); convey informational/success/warning via a leading icon rather than expanding variants.',
    categories: ['feedback'],
    packageRoot: 'packages/rx-feedback',
    sourceFiles: ['src/lib/alert/alert.tsx'],
    targetPrefix: 'src/components/gremorie/feedback/alert',
    srcStrip: 'src/lib/alert/',
    dependencies: ['class-variance-authority'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-progress',
    framework: 'rx',
    title: 'Progress (React)',
    description:
      'Determinate progress indicator (0-100) built on Radix Progress. Use when percent complete is known (uploads, multi-step forms, batch jobs); for unknown duration prefer Skeleton or a spinner.',
    categories: ['feedback'],
    packageRoot: 'packages/rx-feedback',
    sourceFiles: ['src/lib/progress/progress.tsx'],
    targetPrefix: 'src/components/gremorie/feedback/progress',
    srcStrip: 'src/lib/progress/',
    dependencies: ['radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-skeleton',
    framework: 'rx',
    title: 'Skeleton (React)',
    description:
      'Placeholder block for loading states - a pulsing rectangle that reserves layout space so there is no shift when data arrives. Honors `prefers-reduced-motion` automatically.',
    categories: ['feedback'],
    packageRoot: 'packages/rx-feedback',
    sourceFiles: ['src/lib/skeleton/skeleton.tsx'],
    targetPrefix: 'src/components/gremorie/feedback/skeleton',
    srcStrip: 'src/lib/skeleton/',
    dependencies: [],
    registryDependencies: ['rx-utils'],
  },

  // ---------------------------------------------------------------------------
  // React (rx-*): navigation primitives
  // ---------------------------------------------------------------------------
  {
    name: 'rx-breadcrumb',
    framework: 'rx',
    title: 'Breadcrumb (React)',
    description:
      'Hierarchical trail - composable Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage, BreadcrumbSeparator, BreadcrumbEllipsis. Use to show the current location within a nested structure.',
    categories: ['navigation'],
    packageRoot: 'packages/rx-navigation',
    sourceFiles: ['src/lib/breadcrumb/breadcrumb.tsx'],
    targetPrefix: 'src/components/gremorie/navigation/breadcrumb',
    srcStrip: 'src/lib/breadcrumb/',
    dependencies: ['radix-ui', 'lucide-react'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-menubar',
    framework: 'rx',
    title: 'Menubar (React)',
    description:
      'Horizontal multi-menu bar built on Radix Menubar - desktop-style File/Edit/View menus with full keyboard navigation, sub-menus, checkbox and radio items.',
    categories: ['navigation'],
    packageRoot: 'packages/rx-navigation',
    sourceFiles: ['src/lib/menubar/menubar.tsx'],
    targetPrefix: 'src/components/gremorie/navigation/menubar',
    srcStrip: 'src/lib/menubar/',
    dependencies: ['radix-ui', 'lucide-react'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-navigation-menu',
    framework: 'rx',
    title: 'Navigation Menu (React)',
    description:
      'Top-level mega-menu built on Radix NavigationMenu - reveals secondary content panels on hover/focus. Use for site headers with grouped link clusters and feature highlights.',
    categories: ['navigation'],
    packageRoot: 'packages/rx-navigation',
    sourceFiles: ['src/lib/navigation-menu/navigation-menu.tsx'],
    targetPrefix: 'src/components/gremorie/navigation/navigation-menu',
    srcStrip: 'src/lib/navigation-menu/',
    dependencies: ['radix-ui', 'lucide-react', 'class-variance-authority'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-pagination',
    framework: 'rx',
    title: 'Pagination (React)',
    description:
      'Page navigation surface - composable Pagination, PaginationContent, PaginationItem, PaginationLink, PaginationPrevious, PaginationNext, PaginationEllipsis. Anchor tags by default; pass a custom component via PaginationLink for client-side routers.',
    categories: ['navigation'],
    packageRoot: 'packages/rx-navigation',
    sourceFiles: ['src/lib/pagination/pagination.tsx'],
    targetPrefix: 'src/components/gremorie/navigation/pagination',
    srcStrip: 'src/lib/pagination/',
    dependencies: ['lucide-react'],
    registryDependencies: ['rx-utils', 'rx-button'],
  },
  {
    name: 'rx-sidebar',
    framework: 'rx',
    title: 'Sidebar (React)',
    description:
      'Composable app-shell sidebar - SidebarProvider, Sidebar, SidebarTrigger, SidebarMenu plus mobile drawer integration. Cookie-persisted collapsed state, keyboard shortcut, full keyboard navigation. The largest navigation primitive in the registry.',
    categories: ['navigation'],
    packageRoot: 'packages/rx-navigation',
    sourceFiles: ['src/lib/sidebar/sidebar.tsx'],
    targetPrefix: 'src/components/gremorie/navigation/sidebar',
    srcStrip: 'src/lib/sidebar/',
    dependencies: ['radix-ui', 'lucide-react', 'class-variance-authority'],
    registryDependencies: [
      'rx-utils',
      'rx-button',
      'rx-input',
      'rx-separator',
      'rx-skeleton',
      'rx-sheet',
      'rx-tooltip',
    ],
  },
  {
    name: 'rx-tabs',
    framework: 'rx',
    title: 'Tabs (React)',
    description:
      'Tabbed content switcher built on Radix Tabs - Tabs, TabsList, TabsTrigger, TabsContent. Use for sibling content panels that share a context (settings sections, profile pages).',
    categories: ['navigation'],
    packageRoot: 'packages/rx-navigation',
    sourceFiles: ['src/lib/tabs/tabs.tsx'],
    targetPrefix: 'src/components/gremorie/navigation/tabs',
    srcStrip: 'src/lib/tabs/',
    dependencies: ['radix-ui'],
    registryDependencies: ['rx-utils'],
  },

  // ---------------------------------------------------------------------------
  // React (rx-*): forms - extended (added after pilot)
  // ---------------------------------------------------------------------------
  {
    name: 'rx-button-group',
    framework: 'rx',
    title: 'Button Group (React)',
    description:
      'Cluster of related buttons that share a stroke. Composable ButtonGroup, ButtonGroupText, ButtonGroupSeparator. Horizontal or vertical, with optional inner Separator.',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/button-group/button-group.tsx'],
    targetPrefix: 'src/components/gremorie/forms/button-group',
    srcStrip: 'src/lib/button-group/',
    dependencies: ['class-variance-authority', 'radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-calendar',
    framework: 'rx',
    title: 'Calendar (React)',
    description:
      'Date grid built on react-day-picker - single or range selection, multi-month layout, weekday header, keyboard navigation. Pair with Popover for the canonical DatePicker pattern.',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/calendar/calendar.tsx'],
    targetPrefix: 'src/components/gremorie/forms/calendar',
    srcStrip: 'src/lib/calendar/',
    dependencies: ['lucide-react', 'react-day-picker'],
    registryDependencies: ['rx-utils', 'rx-button'],
  },
  {
    name: 'rx-checkbox',
    framework: 'rx',
    title: 'Checkbox (React)',
    description:
      'Binary or tri-state checkbox built on Radix Checkbox. Use for multi-select lists, terms acceptance, settings toggles. For mutually exclusive choices use RadioGroup; for on/off use Switch.',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/checkbox/checkbox.tsx'],
    targetPrefix: 'src/components/gremorie/forms/checkbox',
    srcStrip: 'src/lib/checkbox/',
    dependencies: ['radix-ui', 'lucide-react'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-form',
    framework: 'rx',
    title: 'Form (React)',
    description:
      'React Hook Form integration - Form, FormField, FormItem, FormLabel, FormControl, FormDescription, FormMessage. Wires field state, validation errors, and accessibility attributes.',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/form/form.tsx'],
    targetPrefix: 'src/components/gremorie/forms/form',
    srcStrip: 'src/lib/form/',
    dependencies: ['radix-ui', 'react-hook-form'],
    registryDependencies: ['rx-utils', 'rx-label'],
  },
  {
    name: 'rx-input-otp',
    framework: 'rx',
    title: 'Input OTP (React)',
    description:
      'One-time password input built on input-otp - keyboard-driven, paste-friendly, slot-based. Use for 2FA codes, magic links, SMS verification.',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/input-otp/input-otp.tsx'],
    targetPrefix: 'src/components/gremorie/forms/input-otp',
    srcStrip: 'src/lib/input-otp/',
    dependencies: ['input-otp', 'lucide-react'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-radio-group',
    framework: 'rx',
    title: 'Radio Group (React)',
    description:
      'Mutually exclusive choice group built on Radix RadioGroup. Use for 2-7 distinct options. For binary on/off use Switch; for many options use Select.',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/radio-group/radio-group.tsx'],
    targetPrefix: 'src/components/gremorie/forms/radio-group',
    srcStrip: 'src/lib/radio-group/',
    dependencies: ['radix-ui', 'lucide-react'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-slider',
    framework: 'rx',
    title: 'Slider (React)',
    description:
      'Range slider built on Radix Slider - single value or range (two thumbs), with step + min/max. Use for continuous values (volume, opacity, price range).',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/slider/slider.tsx'],
    targetPrefix: 'src/components/gremorie/forms/slider',
    srcStrip: 'src/lib/slider/',
    dependencies: ['radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-switch',
    framework: 'rx',
    title: 'Switch (React)',
    description:
      'Binary on/off toggle built on Radix Switch. Use for instant-effect settings (dark mode, notifications). For form fields that need explicit "save", prefer Checkbox.',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/switch/switch.tsx'],
    targetPrefix: 'src/components/gremorie/forms/switch',
    srcStrip: 'src/lib/switch/',
    dependencies: ['radix-ui'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-toggle',
    framework: 'rx',
    title: 'Toggle (React)',
    description:
      'Two-state press-button built on Radix Toggle. Use for inline formatting controls (bold, italic) or visibility toggles. For multi-option clusters use ToggleGroup.',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/toggle/toggle.tsx'],
    targetPrefix: 'src/components/gremorie/forms/toggle',
    srcStrip: 'src/lib/toggle/',
    dependencies: ['radix-ui', 'class-variance-authority'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-toggle-group',
    framework: 'rx',
    title: 'Toggle Group (React)',
    description:
      'Mutually exclusive or multi-select cluster of Toggle items, built on Radix ToggleGroup. Use for inline option pickers (text alignment, view mode, filter chips).',
    categories: ['forms'],
    packageRoot: 'packages/rx-forms',
    sourceFiles: ['src/lib/toggle-group/toggle-group.tsx'],
    targetPrefix: 'src/components/gremorie/forms/toggle-group',
    srcStrip: 'src/lib/toggle-group/',
    dependencies: ['radix-ui', 'class-variance-authority'],
    registryDependencies: ['rx-utils', 'rx-toggle'],
  },

  {
    name: 'rx-prompt-input',
    framework: 'rx',
    title: 'Prompt Input (React)',
    description:
      'PromptInput family for AI chat surfaces - state machine, drag-drop, paste-to-attach, status-driven Submit. Full Bridge parity: InputGroup composition (InputGroupButton + InputGroupTextarea), ActionMenu (dropdown), ModelSelector (select), attachment HoverCard previews, Speech button (Web Speech API), Command palette wrappers, Cmd+K floating palette via CommandDialog, and Tabs panels.',
    categories: ['ai', 'forms'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/prompt-input/prompt-input.tsx'],
    targetPrefix: 'src/components/gremorie/ai/prompt-input',
    srcStrip: 'src/lib/prompt-input/',
    dependencies: ['lucide-react'],
    registryDependencies: [
      'rx-utils',
      'rx-button',
      'rx-input-group',
      'rx-select',
      'rx-dialog',
      'rx-dropdown-menu',
      'rx-hover-card',
      'rx-command',
    ],
  },

  // ============================================================
  // Fase 5j - Batch 1: Chatbot family (16 primitives)
  // ============================================================
  {
    name: 'rx-shimmer',
    framework: 'rx',
    title: 'Shimmer (React)',
    description:
      'Animated text shimmer for streaming/loading hints. Uses motion (Framer Motion v12) to slide a gradient across text. Tiny dependency-free primitive used by Reasoning and Plan to mark "thinking" steps.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/shimmer/shimmer.tsx'],
    targetPrefix: 'src/components/gremorie/ai/shimmer',
    srcStrip: 'src/lib/shimmer/',
    dependencies: ['motion'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-suggestion',
    framework: 'rx',
    title: 'Suggestion (React)',
    description:
      'Horizontal scrollable pills of prompt suggestions. Each Suggestion is a rounded Button - the Suggestions wrapper handles overflow with a hidden ScrollArea scrollbar. Use above the prompt input for starter prompts.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/suggestion/suggestion.tsx'],
    targetPrefix: 'src/components/gremorie/ai/suggestion',
    srcStrip: 'src/lib/suggestion/',
    dependencies: [],
    registryDependencies: ['rx-utils', 'rx-button', 'rx-scroll-area'],
  },
  {
    name: 'rx-message',
    framework: 'rx',
    title: 'Message (React)',
    description:
      'Atomic chat message with role-aware layout (user right-aligned, assistant left). Composable surface: MessageContent + MessageResponse (Streamdown markdown), MessageAttachments + MessageAttachment, MessageToolbar with MessageActions, and MessageBranch + MessageBranchSelector + MessageBranchPrevious/Next for regeneration alternatives.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/message/message.tsx'],
    targetPrefix: 'src/components/gremorie/ai/message',
    srcStrip: 'src/lib/message/',
    dependencies: ['ai', 'streamdown'],
    registryDependencies: [
      'rx-utils',
      'rx-button',
      'rx-button-group',
      'rx-tooltip',
    ],
  },
  {
    name: 'rx-conversation',
    framework: 'rx',
    title: 'Conversation (React)',
    description:
      'Scroll-to-bottom container for chat messages. Uses use-stick-to-bottom under the hood: ConversationContent stays anchored to the bottom while new messages stream in. ConversationScrollButton appears when the user scrolls up and snaps back when clicked. ConversationEmptyState renders centered placeholder content.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/conversation/conversation.tsx'],
    targetPrefix: 'src/components/gremorie/ai/conversation',
    srcStrip: 'src/lib/conversation/',
    dependencies: ['use-stick-to-bottom'],
    registryDependencies: ['rx-utils', 'rx-button'],
  },
  {
    name: 'rx-reasoning',
    framework: 'rx',
    title: 'Reasoning (React)',
    description:
      'Collapsible "thinking" block for visible chain-of-thought. Auto-opens while isStreaming, tracks duration, auto-closes after streaming ends. ReasoningContent renders Streamdown markdown; ReasoningTrigger uses Shimmer to mark live thought.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/reasoning/reasoning.tsx'],
    targetPrefix: 'src/components/gremorie/ai/reasoning',
    srcStrip: 'src/lib/reasoning/',
    dependencies: [
      '@radix-ui/react-use-controllable-state',
      'streamdown',
    ],
    registryDependencies: ['rx-utils', 'rx-collapsible', 'rx-shimmer'],
  },
  {
    name: 'rx-chain-of-thought',
    framework: 'rx',
    title: 'Chain of Thought (React)',
    description:
      'Step-by-step reasoning visualizer. ChainOfThoughtStep renders each thought with status (pending/active/complete), icon, and optional ChainOfThoughtStepBody. Supports nested ChainOfThoughtSearch with Badge result chips. Wraps a Collapsible for show/hide.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/chain-of-thought/chain-of-thought.tsx'],
    targetPrefix: 'src/components/gremorie/ai/chain-of-thought',
    srcStrip: 'src/lib/chain-of-thought/',
    dependencies: ['@radix-ui/react-use-controllable-state'],
    registryDependencies: ['rx-utils', 'rx-badge', 'rx-collapsible'],
  },
  {
    name: 'rx-task',
    framework: 'rx',
    title: 'Task (React)',
    description:
      'Collapsible item list for an agent task. TaskTrigger shows status + summary, TaskContent holds TaskItem children. TaskItemFile renders inline file badges (e.g. "edited app.tsx"). Use for multi-step tool-use traces in the conversation.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/task/task.tsx'],
    targetPrefix: 'src/components/gremorie/ai/task',
    srcStrip: 'src/lib/task/',
    dependencies: [],
    registryDependencies: ['rx-utils', 'rx-collapsible'],
  },
  {
    name: 'rx-tool',
    framework: 'rx',
    title: 'Tool (React)',
    description:
      'Tool-use trace block. ToolHeader shows the tool name + state Badge (input-streaming, input-available, output-available, output-error). ToolContent reveals ToolInput (JSON params), ToolOutput (formatted result), and ToolErrors. Built on Collapsible + CodeBlock.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/tool/tool.tsx'],
    targetPrefix: 'src/components/gremorie/ai/tool',
    srcStrip: 'src/lib/tool/',
    dependencies: ['ai'],
    registryDependencies: [
      'rx-utils',
      'rx-badge',
      'rx-collapsible',
      'rx-code-block',
    ],
  },
  {
    name: 'rx-sources',
    framework: 'rx',
    title: 'Sources (React)',
    description:
      'Citations cluster for RAG responses. SourcesTrigger shows "N sources" toggle, SourcesContent reveals the list. Each Source is a hyperlink with optional favicon. Use to attribute model output to retrieved documents.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/sources/sources.tsx'],
    targetPrefix: 'src/components/gremorie/ai/sources',
    srcStrip: 'src/lib/sources/',
    dependencies: [],
    registryDependencies: ['rx-utils', 'rx-collapsible'],
  },
  {
    name: 'rx-inline-citation',
    framework: 'rx',
    title: 'Inline Citation (React)',
    description:
      'Footnote-style inline citation marker. Hovers reveal a HoverCard with a Carousel of source cards (InlineCitationCard, InlineCitationCardTrigger, InlineCitationCardBody, InlineCitationSource, InlineCitationQuote). Use inside MessageResponse to cite passages mid-sentence.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/inline-citation/inline-citation.tsx'],
    targetPrefix: 'src/components/gremorie/ai/inline-citation',
    srcStrip: 'src/lib/inline-citation/',
    dependencies: [],
    registryDependencies: [
      'rx-utils',
      'rx-badge',
      'rx-carousel',
      'rx-hover-card',
    ],
  },
  {
    name: 'rx-plan',
    framework: 'rx',
    title: 'Plan (React)',
    description:
      'Multi-step plan card with Shimmer-marked active step. PlanHeader + PlanTitle + PlanDescription describe the goal; PlanContent lists PlanStep items, each with status. PlanFooter holds CTA Buttons (approve / regenerate). Built on Card + Collapsible.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/plan/plan.tsx'],
    targetPrefix: 'src/components/gremorie/ai/plan',
    srcStrip: 'src/lib/plan/',
    dependencies: [],
    registryDependencies: [
      'rx-utils',
      'rx-button',
      'rx-card',
      'rx-collapsible',
      'rx-shimmer',
    ],
  },
  {
    name: 'rx-checkpoint',
    framework: 'rx',
    title: 'Checkpoint (React)',
    description:
      'Conversation savepoint marker. Renders a labeled bookmark with Separator on each side, plus a Tooltip explaining the state. Use to indicate revertable points in long agent runs.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/checkpoint/checkpoint.tsx'],
    targetPrefix: 'src/components/gremorie/ai/checkpoint',
    srcStrip: 'src/lib/checkpoint/',
    dependencies: [],
    registryDependencies: [
      'rx-utils',
      'rx-button',
      'rx-separator',
      'rx-tooltip',
    ],
  },
  {
    name: 'rx-confirmation',
    framework: 'rx',
    title: 'Confirmation (React)',
    description:
      'Approval prompt for tool calls. Wraps an Alert with ConfirmationRequest, ConfirmationDescription, and ConfirmationActions (Approve / Reject Buttons). Designed for human-in-the-loop tool gates - exposes approved/rejected callbacks with optional reason.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/confirmation/confirmation.tsx'],
    targetPrefix: 'src/components/gremorie/ai/confirmation',
    srcStrip: 'src/lib/confirmation/',
    dependencies: ['ai'],
    registryDependencies: ['rx-utils', 'rx-alert', 'rx-button'],
  },
  {
    name: 'rx-context',
    framework: 'rx',
    title: 'Context (React)',
    description:
      'Token usage display for AI conversations. ContextTrigger shows a circular progress glyph; on hover, ContextContent reveals input/output/total tokens, model max, and cost via tokenlens. Uses Progress + HoverCard.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/context/context.tsx'],
    targetPrefix: 'src/components/gremorie/ai/context',
    srcStrip: 'src/lib/context/',
    dependencies: ['ai', 'tokenlens'],
    registryDependencies: [
      'rx-utils',
      'rx-button',
      'rx-hover-card',
      'rx-progress',
    ],
  },
  {
    name: 'rx-queue',
    framework: 'rx',
    title: 'Queue (React)',
    description:
      'Pending message queue list shown above the prompt input. Each QueueMessage previews text + attachments; the user can dismiss or reorder. Built on Collapsible + ScrollArea.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/queue/queue.tsx'],
    targetPrefix: 'src/components/gremorie/ai/queue',
    srcStrip: 'src/lib/queue/',
    dependencies: [],
    registryDependencies: [
      'rx-utils',
      'rx-button',
      'rx-collapsible',
      'rx-scroll-area',
    ],
  },
  {
    name: 'rx-model-selector',
    framework: 'rx',
    title: 'Model Selector (React)',
    description:
      'Floating model picker dialog. ModelSelectorTrigger opens a Dialog containing a full Command palette - CommandInput, CommandGroup, CommandItem, CommandShortcut, CommandSeparator. Use as a Cmd+K-style model switcher above the chat composer.',
    categories: ['ai', 'chatbot'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/model-selector/model-selector.tsx'],
    targetPrefix: 'src/components/gremorie/ai/model-selector',
    srcStrip: 'src/lib/model-selector/',
    dependencies: [],
    registryDependencies: ['rx-utils', 'rx-command', 'rx-dialog'],
  },

  // ============================================================
  // Fase 5j - Batch 2: Code family (3 primitives)
  // ============================================================
  {
    name: 'rx-artifact',
    framework: 'rx',
    title: 'Artifact (React)',
    description:
      'Generic artifact card for AI-generated objects (code, doc, chart, image preview). ArtifactHeader + ArtifactTitle + ArtifactDescription + ArtifactActions + ArtifactAction + ArtifactClose + ArtifactContent. Use as the chrome wrapper for CodeBlock, WebPreview, Image, or any generated asset.',
    categories: ['ai', 'code'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/artifact/artifact.tsx'],
    targetPrefix: 'src/components/gremorie/ai/artifact',
    srcStrip: 'src/lib/artifact/',
    dependencies: [],
    registryDependencies: ['rx-utils', 'rx-button', 'rx-tooltip'],
  },
  {
    name: 'rx-code-block',
    framework: 'rx',
    title: 'Code Block (React)',
    description:
      'Syntax-highlighted code surface powered by shiki. Lazy-loads codeToHtml on mount; exposes CodeBlockCopyButton with copy/copied state. Pass code + language, optional showLineNumbers; ships dark + light themes by default.',
    categories: ['ai', 'code'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/code-block/code-block.tsx'],
    targetPrefix: 'src/components/gremorie/ai/code-block',
    srcStrip: 'src/lib/code-block/',
    dependencies: ['shiki'],
    registryDependencies: ['rx-utils', 'rx-button'],
  },
  {
    name: 'rx-web-preview',
    framework: 'rx',
    title: 'Web Preview (React)',
    description:
      'Sandboxed browser preview for AI-generated sites. WebPreviewNavigation has back/forward/refresh, WebPreviewUrl is a navigable Input, WebPreviewBody renders an iframe with the current URL, and WebPreviewConsole (Collapsible) shows console logs and errors below.',
    categories: ['ai', 'code'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/web-preview/web-preview.tsx'],
    targetPrefix: 'src/components/gremorie/ai/web-preview',
    srcStrip: 'src/lib/web-preview/',
    dependencies: [],
    registryDependencies: [
      'rx-utils',
      'rx-button',
      'rx-collapsible',
      'rx-input',
      'rx-tooltip',
    ],
  },

  // ============================================================
  // Fase 5j - Batch 3: Workflow family (7 primitives)
  // ============================================================
  {
    name: 'rx-canvas',
    framework: 'rx',
    title: 'Canvas (React)',
    description:
      'ReactFlow canvas surface for visual workflows / agent graphs. Pre-configured for pan-on-scroll, drag-selection, and deletable nodes via Backspace/Delete. Wraps @xyflow/react ReactFlow + Background.',
    categories: ['ai', 'workflow'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/canvas/canvas.tsx'],
    targetPrefix: 'src/components/gremorie/ai/canvas',
    srcStrip: 'src/lib/canvas/',
    dependencies: ['@xyflow/react'],
    registryDependencies: [],
  },
  {
    name: 'rx-connection',
    framework: 'rx',
    title: 'Connection (React)',
    description:
      'Animated bezier-curve connection line component for @xyflow/react. Renders a smoothly curved path with a circle terminator while the user is dragging a new edge. Pass as the connectionLineComponent prop on Canvas.',
    categories: ['ai', 'workflow'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/connection/connection.tsx'],
    targetPrefix: 'src/components/gremorie/ai/connection',
    srcStrip: 'src/lib/connection/',
    dependencies: ['@xyflow/react'],
    registryDependencies: [],
  },
  {
    name: 'rx-controls',
    framework: 'rx',
    title: 'Controls (React)',
    description:
      'Styled wrapper around @xyflow/react Controls (zoom in/out, fit view, lock). Pre-themed to match Gremorie - rounded, bordered, secondary-tinted buttons. Drop inside a Canvas as a child for floating zoom controls.',
    categories: ['ai', 'workflow'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/controls/controls.tsx'],
    targetPrefix: 'src/components/gremorie/ai/controls',
    srcStrip: 'src/lib/controls/',
    dependencies: ['@xyflow/react'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-edge',
    framework: 'rx',
    title: 'Edge (React)',
    description:
      'Edge variants for @xyflow/react: Temporary (simple-bezier curve for in-progress connections) and Animated (gradient-flowing bezier for active flows). Register via edgeTypes={{ temporary: Temporary, animated: Animated }} on Canvas.',
    categories: ['ai', 'workflow'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/edge/edge.tsx'],
    targetPrefix: 'src/components/gremorie/ai/edge',
    srcStrip: 'src/lib/edge/',
    dependencies: ['@xyflow/react'],
    registryDependencies: [],
  },
  {
    name: 'rx-node',
    framework: 'rx',
    title: 'Node (React)',
    description:
      'Card-based node for @xyflow/react graphs. Wraps Gremorie Card + CardHeader/Title/Description/Content/Footer/Action to give each node consistent chrome. Accepts handles { target, source } booleans to declare which sides expose connection Handles.',
    categories: ['ai', 'workflow'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/node/node.tsx'],
    targetPrefix: 'src/components/gremorie/ai/node',
    srcStrip: 'src/lib/node/',
    dependencies: ['@xyflow/react'],
    registryDependencies: ['rx-utils', 'rx-card'],
  },
  {
    name: 'rx-panel',
    framework: 'rx',
    title: 'Panel (React)',
    description:
      'Floating positioned panel inside a @xyflow/react Canvas. Pre-themed - bordered, rounded, card-tinted, padded - for stacking minimap, layers, or context controls in a corner of the workflow.',
    categories: ['ai', 'workflow'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/panel/panel.tsx'],
    targetPrefix: 'src/components/gremorie/ai/panel',
    srcStrip: 'src/lib/panel/',
    dependencies: ['@xyflow/react'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-toolbar',
    framework: 'rx',
    title: 'Toolbar (React)',
    description:
      'Per-node floating toolbar (NodeToolbar from @xyflow/react). Anchored below the node by default - use for context actions on selection (delete, duplicate, configure).',
    categories: ['ai', 'workflow'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/toolbar/toolbar.tsx'],
    targetPrefix: 'src/components/gremorie/ai/toolbar',
    srcStrip: 'src/lib/toolbar/',
    dependencies: ['@xyflow/react'],
    registryDependencies: ['rx-utils'],
  },

  // ============================================================
  // Fase 5j - Batch 4: Utilities family (2 primitives)
  // ============================================================
  {
    name: 'rx-image',
    framework: 'rx',
    title: 'Image (React)',
    description:
      'Tiny wrapper that renders an Experimental_GeneratedImage (Vercel AI SDK) as a data-URI <img>. Use to display model-generated images returned from generateImage() / experimental tool output.',
    categories: ['ai', 'utilities'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/image/image.tsx'],
    targetPrefix: 'src/components/gremorie/ai/image',
    srcStrip: 'src/lib/image/',
    dependencies: ['ai'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-open-in-chat',
    framework: 'rx',
    title: 'Open in Chat (React)',
    description:
      'Dropdown that opens the current page in an external chat (ChatGPT, Claude, Gemini, T3 Chat, ...). Provides preset providers (github, chatgpt, claude, gemini, t3) and accepts custom OpenInChatItem entries.',
    categories: ['ai', 'utilities'],
    packageRoot: 'packages/rx-ai',
    sourceFiles: ['src/lib/open-in-chat/open-in-chat.tsx'],
    targetPrefix: 'src/components/gremorie/ai/open-in-chat',
    srcStrip: 'src/lib/open-in-chat/',
    dependencies: [],
    registryDependencies: ['rx-utils', 'rx-button', 'rx-dropdown-menu'],
  },

  // ============================================================
  // Fase 5k - React data viz (8 primitives - closes Bridge parity)
  // Headless chart engine + 7 styled charts.
  // Mirrors ng-data structure: a shared ng-chart-equivalent base
  // (rx-chart) carries the headless primitives, each styled chart
  // depends on it. Brings the React edition to parity with the
  // Angular edition and closes the data-viz gap from Bridge.
  // ============================================================
  {
    name: 'rx-chart',
    framework: 'rx',
    title: 'Chart (React)',
    description:
      'Headless chart engine for the React edition - chart-context (React Context + hooks), scales, axis, cartesian-grid, chart-frame, plus shape helpers (area, line, bar, scatter, pie, polar, radar, radial-bar). Shared base for every styled chart.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/rx-data',
    sourceFiles: [
      'src/lib/headless/types.ts',
      'src/lib/headless/format.ts',
      'src/lib/headless/scales.ts',
      'src/lib/headless/shape.ts',
      'src/lib/headless/domain.ts',
      'src/lib/headless/polar.ts',
      'src/lib/headless/chart-context.tsx',
      'src/lib/headless/chart-frame.tsx',
      'src/lib/headless/axis.tsx',
      'src/lib/headless/cartesian-grid.tsx',
      'src/lib/headless/area.tsx',
      'src/lib/headless/line.tsx',
      'src/lib/headless/bar.tsx',
      'src/lib/headless/scatter.tsx',
      'src/lib/headless/pie.tsx',
      'src/lib/headless/radar.tsx',
      'src/lib/headless/radial-bar.tsx',
      'src/lib/headless/index.ts',
    ],
    targetPrefix: 'src/components/gremorie/data/headless',
    srcStrip: 'src/lib/headless/',
    dependencies: ['react', 'd3-scale', 'd3-shape', 'd3-format'],
    registryDependencies: ['rx-utils'],
  },
  {
    name: 'rx-area-chart',
    framework: 'rx',
    title: 'Area Chart (React)',
    description:
      'Styled area chart - cumulative quantity over a continuous domain. Uses the rx-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/rx-data',
    sourceFiles: ['src/lib/area-chart/area-chart.tsx'],
    targetPrefix: 'src/components/gremorie/data/area-chart',
    srcStrip: 'src/lib/area-chart/',
    dependencies: ['react'],
    registryDependencies: ['rx-utils', 'rx-chart'],
  },
  {
    name: 'rx-line-chart',
    framework: 'rx',
    title: 'Line Chart (React)',
    description:
      'Styled line chart - trends over a continuous domain. Uses the rx-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/rx-data',
    sourceFiles: ['src/lib/line-chart/line-chart.tsx'],
    targetPrefix: 'src/components/gremorie/data/line-chart',
    srcStrip: 'src/lib/line-chart/',
    dependencies: ['react'],
    registryDependencies: ['rx-utils', 'rx-chart'],
  },
  {
    name: 'rx-bar-chart',
    framework: 'rx',
    title: 'Bar Chart (React)',
    description:
      'Styled grouped bar chart - compare values across categories with one bar per series in each band. Uses the rx-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/rx-data',
    sourceFiles: ['src/lib/bar-chart/bar-chart.tsx'],
    targetPrefix: 'src/components/gremorie/data/bar-chart',
    srcStrip: 'src/lib/bar-chart/',
    dependencies: ['react'],
    registryDependencies: ['rx-utils', 'rx-chart'],
  },
  {
    name: 'rx-scatter-chart',
    framework: 'rx',
    title: 'Scatter Chart (React)',
    description:
      'Styled scatter chart - show correlation between a numeric X field and one or more Y series. Uses the rx-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/rx-data',
    sourceFiles: ['src/lib/scatter-chart/scatter-chart.tsx'],
    targetPrefix: 'src/components/gremorie/data/scatter-chart',
    srcStrip: 'src/lib/scatter-chart/',
    dependencies: ['react'],
    registryDependencies: ['rx-utils', 'rx-chart'],
  },
  {
    name: 'rx-pie-chart',
    framework: 'rx',
    title: 'Pie Chart (React)',
    description:
      'Styled pie / donut chart - parts of a whole, one slice per data row. Uses the rx-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/rx-data',
    sourceFiles: ['src/lib/pie-chart/pie-chart.tsx'],
    targetPrefix: 'src/components/gremorie/data/pie-chart',
    srcStrip: 'src/lib/pie-chart/',
    dependencies: ['react'],
    registryDependencies: ['rx-utils', 'rx-chart'],
  },
  {
    name: 'rx-radar-chart',
    framework: 'rx',
    title: 'Radar Chart (React)',
    description:
      'Styled radar chart - compare series across multiple axes that share a radial domain. Uses the rx-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/rx-data',
    sourceFiles: ['src/lib/radar-chart/radar-chart.tsx'],
    targetPrefix: 'src/components/gremorie/data/radar-chart',
    srcStrip: 'src/lib/radar-chart/',
    dependencies: ['react'],
    registryDependencies: ['rx-utils', 'rx-chart'],
  },
  {
    name: 'rx-radial-chart',
    framework: 'rx',
    title: 'Radial Chart (React)',
    description:
      'Styled radial bar chart - concentric rings, one per data row, each sweep proportional to its value. Uses the rx-chart headless primitives.',
    categories: ['data', 'charts'],
    packageRoot: 'packages/rx-data',
    sourceFiles: ['src/lib/radial-chart/radial-chart.tsx'],
    targetPrefix: 'src/components/gremorie/data/radial-chart',
    srcStrip: 'src/lib/radial-chart/',
    dependencies: ['react'],
    registryDependencies: ['rx-utils', 'rx-chart'],
  },

  // ---------------------------------------------------------------------------
  // React (rx-*): featured blocks
  // ---------------------------------------------------------------------------
  {
    name: 'block-sign-in',
    framework: 'rx',
    title: 'Sign-in block',
    description:
      'Authentication card with a GitHub provider above an email/password field group. Composes Card, Button, Separator, Label, and Input.',
    categories: ['blocks', 'auth'],
    packageRoot: 'apps/docs/components/preview/blocks',
    sourceFiles: ['sign-in.tsx'],
    targetPrefix: 'src/components/gremorie/blocks/sign-in',
    srcStrip: '',
    dependencies: ['react', 'lucide-react'],
    registryDependencies: [
      'rx-utils',
      'rx-button',
      'rx-card',
      'rx-input',
      'rx-label',
      'rx-separator',
    ],
  },
  {
    name: 'block-dashboard',
    framework: 'rx',
    title: 'Dashboard block',
    description:
      'Analytics surface: four KPI cards, a revenue bar chart, and a recent-transactions table. Composes Card, Badge, Table, BarChart, and Button.',
    categories: ['blocks', 'dashboard'],
    packageRoot: 'apps/docs/components/preview/blocks',
    sourceFiles: ['dashboard.tsx'],
    targetPrefix: 'src/components/gremorie/blocks/dashboard',
    srcStrip: '',
    dependencies: ['react', 'lucide-react'],
    registryDependencies: [
      'rx-utils',
      'rx-button',
      'rx-card',
      'rx-badge',
      'rx-table',
      'rx-bar-chart',
    ],
  },
  {
    name: 'block-chat-surface',
    framework: 'rx',
    title: 'Chat surface block',
    description:
      'AI chat surface: Conversation log with stick-to-bottom scrolling, user and assistant Messages, Reasoning collapsible, and a PromptInput composer.',
    categories: ['blocks', 'ai', 'chat'],
    packageRoot: 'apps/docs/components/preview/blocks',
    sourceFiles: ['chat-surface.tsx'],
    targetPrefix: 'src/components/gremorie/blocks/chat-surface',
    srcStrip: '',
    dependencies: ['react'],
    registryDependencies: [
      'rx-utils',
      'rx-conversation',
      'rx-message',
      'rx-reasoning',
      'rx-prompt-input',
    ],
  },
  {
    name: 'block-settings-form',
    framework: 'rx',
    title: 'Settings form block',
    description:
      'Settings page: Profile, Notifications, and Appearance cards with a sticky save bar. Composes Card, Avatar, Input, Label, Switch, Slider, and Button.',
    categories: ['blocks', 'forms', 'settings'],
    packageRoot: 'apps/docs/components/preview/blocks',
    sourceFiles: ['settings-form.tsx'],
    targetPrefix: 'src/components/gremorie/blocks/settings-form',
    srcStrip: '',
    dependencies: ['react'],
    registryDependencies: [
      'rx-utils',
      'rx-button',
      'rx-card',
      'rx-avatar',
      'rx-input',
      'rx-label',
      'rx-switch',
      'rx-slider',
    ],
  },
  {
    name: 'block-marketing-hero',
    framework: 'rx',
    title: 'Marketing hero block',
    description:
      'Landing hero: brand-tinted halo, eyebrow Badge, headline with brand-highlighted span, dual CTA, and a window mockup Card.',
    categories: ['blocks', 'marketing'],
    packageRoot: 'apps/docs/components/preview/blocks',
    sourceFiles: ['marketing-hero.tsx'],
    targetPrefix: 'src/components/gremorie/blocks/marketing-hero',
    srcStrip: '',
    dependencies: ['react', 'lucide-react'],
    registryDependencies: ['rx-utils', 'rx-button', 'rx-card', 'rx-badge'],
  },
  {
    name: 'block-empty-state',
    framework: 'rx',
    title: 'Empty state block',
    description:
      'Empty-state pattern: dashed-border container, centered icon medallion, headline, description, and dual CTA. Composes Button + lucide icons.',
    categories: ['blocks', 'empty-state'],
    packageRoot: 'apps/docs/components/preview/blocks',
    sourceFiles: ['empty-state.tsx'],
    targetPrefix: 'src/components/gremorie/blocks/empty-state',
    srcStrip: '',
    dependencies: ['react', 'lucide-react'],
    registryDependencies: ['rx-utils', 'rx-button'],
  },

  // ---------------------------------------------------------------------------
  // React (rx-*): featured artifacts (one per category)
  // ---------------------------------------------------------------------------
  {
    name: 'artifact-chart-bar',
    framework: 'rx',
    title: 'Chart (bar) artifact',
    description:
      'Bar chart artifact rendering a schema-driven dataset emitted by the model. Composes BarChart (rx-data) with Card + Badge for framing.',
    categories: ['artifacts', 'chart'],
    packageRoot: 'apps/docs/components/preview/artifacts',
    sourceFiles: ['chart-bar.tsx'],
    targetPrefix: 'src/components/gremorie/artifacts/chart-bar',
    srcStrip: '',
    dependencies: ['react'],
    registryDependencies: ['rx-utils', 'rx-card', 'rx-badge', 'rx-bar-chart'],
  },
  {
    name: 'artifact-code-block',
    framework: 'rx',
    title: 'Code block artifact',
    description:
      'Syntax-highlighted code artifact with copy-to-clipboard. Composes CodeBlock (rx-ai) with Card + Badge for framing.',
    categories: ['artifacts', 'code'],
    packageRoot: 'apps/docs/components/preview/artifacts',
    sourceFiles: ['code-block.tsx'],
    targetPrefix: 'src/components/gremorie/artifacts/code-block',
    srcStrip: '',
    dependencies: ['react'],
    registryDependencies: ['rx-utils', 'rx-card', 'rx-badge', 'rx-code-block'],
  },
  {
    name: 'artifact-markdown-doc',
    framework: 'rx',
    title: 'Markdown document artifact',
    description:
      'Document artifact rendering streamed Markdown with prose typography. Composes Card + Badge with a prose article wrapper.',
    categories: ['artifacts', 'document'],
    packageRoot: 'apps/docs/components/preview/artifacts',
    sourceFiles: ['markdown-doc.tsx'],
    targetPrefix: 'src/components/gremorie/artifacts/markdown-doc',
    srcStrip: '',
    dependencies: ['react'],
    registryDependencies: ['rx-utils', 'rx-card', 'rx-badge'],
  },
  {
    name: 'artifact-data-table',
    framework: 'rx',
    title: 'Data table artifact',
    description:
      'Filterable table artifact rendering JSON rows. Composes Table (rx-display) with Input filter, Badge status, and lucide Search icon.',
    categories: ['artifacts', 'data'],
    packageRoot: 'apps/docs/components/preview/artifacts',
    sourceFiles: ['data-table.tsx'],
    targetPrefix: 'src/components/gremorie/artifacts/data-table',
    srcStrip: '',
    dependencies: ['react', 'lucide-react'],
    registryDependencies: [
      'rx-utils',
      'rx-card',
      'rx-badge',
      'rx-table',
      'rx-input',
    ],
  },
  {
    name: 'artifact-form-schema',
    framework: 'rx',
    title: 'Form (schema) artifact',
    description:
      'Form artifact generated from a JSON field schema with submit. Composes Input, Checkbox, Label, Button (rx-forms) with Card + Badge.',
    categories: ['artifacts', 'form'],
    packageRoot: 'apps/docs/components/preview/artifacts',
    sourceFiles: ['form-schema.tsx'],
    targetPrefix: 'src/components/gremorie/artifacts/form-schema',
    srcStrip: '',
    dependencies: ['react'],
    registryDependencies: [
      'rx-utils',
      'rx-card',
      'rx-badge',
      'rx-input',
      'rx-checkbox',
      'rx-label',
      'rx-button',
    ],
  },
  {
    name: 'artifact-calculator',
    framework: 'rx',
    title: 'Calculator artifact',
    description:
      'Interactive tool-call artifact with editable inputs, operator toggle, and live result. Composes Input, Label, Button (rx-forms) with Card + Badge.',
    categories: ['artifacts', 'interactive'],
    packageRoot: 'apps/docs/components/preview/artifacts',
    sourceFiles: ['calculator.tsx'],
    targetPrefix: 'src/components/gremorie/artifacts/calculator',
    srcStrip: '',
    dependencies: ['react', 'lucide-react'],
    registryDependencies: [
      'rx-utils',
      'rx-card',
      'rx-badge',
      'rx-input',
      'rx-label',
      'rx-button',
    ],
  },
];
