import { DocsLayout } from "fumadocs-ui/layouts/docs";

import type { ReactNode } from "react";

import { FlagLanguageSwitch } from "@/components/flag-language-switch";
import { getSection } from "@/lib/get-section";
import { baseOptions } from "@/lib/layout.shared";
import { source } from "@/lib/source";

/**
 * Catch-all docs layout.
 *
 * Tabs are NOT hardcoded as an array. They are generated by Fumadocs
 * from each top-level `meta.json` flagged `root: true`, and the icons
 * are styled per-section via `tabs.transform()` — the official pattern
 * from fumadocs.dev (apps/docs/app/docs/layout.tsx on the dev repo).
 *
 * `getSection()` maps the meta's directory to a CSS variable name like
 * `--components-color`; the tab icon then renders inside a colored
 * background on small screens and tinted foreground on the desktop
 * sidebar. Colors live in `app/global.css`.
 */
export default async function Layout({
  params,
  children
}: {
  params: Promise<{ lang: string }>;
  children: ReactNode;
}) {
  const { lang } = await params;
  return (
    <DocsLayout
      // false = sem o seletor de idioma padrão (texto); usamos o de bandeiras
      // no banner. O contexto de locale segue vindo do RootProvider.
      i18n={false}
      {...baseOptions(lang)}
      tree={source.getPageTree(lang)}
      sidebar={{
        collapsible: true,
        // 0 = categorias (folders) fechadas por padrão; só a categoria da
        // página atual abre. Visão geral primeiro, depois as seções/categorias.
        defaultOpenLevel: 0,
        // Seletor de idioma (bandeiras) logo abaixo da busca. Substitui o
        // toggle de texto padrão do Fumadocs (por isso removemos a prop `i18n`;
        // o contexto de locale vem do RootProvider).
        banner: (
          <div key="lang-banner" className="flex justify-end">
            <FlagLanguageSwitch />
          </div>
        ),
        tabs: {
          transform(option, node) {
            const meta = source.getNodeMeta(node);
            if (!meta || !node.icon) return option;
            const color = `var(--${getSection(meta.path)}-color, var(--color-fd-foreground))`;
            return {
              ...option,
              icon: (
                <div
                  className="[&_svg]:size-full rounded-lg size-full text-(--tab-color) max-md:bg-(--tab-color)/10 max-md:border max-md:p-1.5"
                  style={
                    {
                      "--tab-color": color
                    } as React.CSSProperties
                  }
                >
                  {node.icon}
                </div>
              )
            };
          }
        }
      }}
    >
      {children}
    </DocsLayout>
  );
}
